### PR TITLE
Remove the need for shell script shims

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Seems to work good!

Things I haven't yet tested (in progress):
* ERB script
* Puppet lint without args

### CODE REVIEW

**Comment by alexjurkiewicz** [comment]
There's one regression: it lacks coloured output. I'd like to add it with auto-terminal detection. Colour codes cause ugly output in our CI logs if something fails :(

**Comment by alexjurkiewicz** [comment]
Hmm, it doesn't seem trivial to colour output in terminal but not in CI. You can't check if stdout is a tty because the parent process is the pre-commit wrapper :(

Would you prefer the output to remain coloured?

**Review by chriskuehl — APPROVED** [review]
lgtm! thanks for getting rid of the silly wrapper scripts

I'll chat with asottile about this tomorrow and see if he has any ideas about detecting stdout is a tty in order to know if colors are appropriate. But I think you're right -- I don't see any obvious way to check that, given that pre-commit is capturing the output already.

**Comment by alexjurkiewicz** [comment]
It's probably possible to walk up the parent process tree and check for a TTY in the pre-commit parent, but if youse are all part of the official pre-commit team maybe there's an opportunity for something more standardised here, like an env variable passed down to hooks specifying if colour should be used.

**Comment by chriskuehl** [comment]
Confirmed there's not currently a good way to figure out if colors are appropriate. This change still looks good -- thanks!

**Pull request merged**
