### PR TITLE
Simpler hook structure

### PR DESCRIPTION
**Pull request by alexjurkiewicz**
Thanks for collab status, but I'll still run everything through PRs 🙌 

I'm not really sure what the gemspec was used for -- did `pre-commit` use it during environment setup somehow? I'm assuming it did, but can't find any docs explaining the process.

I also removed some Puppet 3-centric advice from the README.

### CODE REVIEW

**Comment by chriskuehl** [comment]
I think the main benefit to doing it the gemspec way with `language: ruby` is that pre-commit will take responsibility for installing the dependencies (just puppet and puppet-lint), which is useful if you don't install them system-wide (and also useful for things like puppet-lint where the system package might be old, but you can grab a new version from rubygems). For example, a lot of our devs like to run the tests on their laptops which don't have puppet or puppet-lint installed, so it's convenient for pre-commit to handle installing it for them.

Sorry if I misunderstood your question from yesterday. I was thinking you were planning to re-write the scripts in Ruby (rather than what it does currently, which is just shell out to Bash from Ruby).

**Comment by alexjurkiewicz** [comment]
Ah ok, I understand how it fits together now. It is really convenient to have pre-commit deal with the puppet/puppet-lint dependencies.

Using this approach, is it possible to support both Puppet 3 & 4 with the same codebase? I can't see an obvious way to do this (although I know very little about Gemfiles -- can you install two versions of Puppet?).

**Comment by chriskuehl** [comment]
Originally I was thinking this repo would need to have two branches (one for puppet 3.x. one for 4.x), but since then pre-commit has added support for "additional_dependencies" which I think could be used instead. Basically the idea would be for this hook repo to stop specifying any version of puppet, and then anybody using these hooks can pass `additional_depenencies: ['puppet==3']` or similar.

They're talked about a little on http://pre-commit.com/

I haven't actually tried this, though -- I'll see if I can make a branch quick where this works.

**Comment by alexjurkiewicz** [comment]
OK, I'll close this PR for now

**Pull request closed without merging**
